# managed by glassine — edit recipients via `glassine allow` / `glassine revoke`
creation_rules:
  - key_groups:
      - age:
          - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+bl01iRKRVYvOtFYSQWqKtqo2N2TG9H5+nGSxJSxE0' # github:DJRHails
          - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJQpQsoOwzcytS+AjXSB7bZbHjI90oX2uf80xNDBjXaL' # github:DJRHails
          - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC/+Ziaqy11tLwos1sVvaBo+kKI14Y/zRtMTUK85rSL8' # github:DJRHails
          - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINUhwKeMY/N/+vFiMr/jjz1GWUZ14XgTfctDphaUIJh5' # github:DJRHails
          - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJe3wmGlGSjzUhnmCGKKrHStmXGyZKQwCGROEfPBdTIP' # github:DJRHails
          - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILGayLhDYjABZUNZKUfOMZeo4zka57Sl12wUHdt0zr7p' # github:DJRHails
          - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIESvGuL264sdGqVwDkWPw/nkSI/cQKCnqCOhzEigF6xV'
